service: sentiment-analysis-serverless

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    CUSTOMER_FEEDBACK_TABLE: ${self:custom.CustomerFeedbackTable.name}
    NUMBER_OF_RECORDS_TO_PROCESS: 10 #Max is 25 records, hard limit by AWS Comprehend batch
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "*"
      Resource:
        - "*"

functions:
  s3Trigger:
    handler: src/handlers/s3Trigger.handler
    environment:
      stage: ${self:provider.stage}
      statemachine_arn: arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:hellostepfunc1
    events:
      - s3:
          bucket: sentiment-analysis-serverless-source
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
  readFeedback:
    handler: src/handlers/readFeedback.handler
  computeSentiment:
    handler: src/handlers/computeSentiment.handler
  iterator:
    handler: src/handlers/iterator.handler

stepFunctions:
  stateMachines:
    hellostepfunc1:
      name: "hellostepfunc1"
      definition:
        Comment: "Read CSV files and do sentiment analysis"
        StartAt: ReadFeedbackFromS3
        States:
          ReadFeedbackFromS3:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-readFeedback"
            Next: ProcessAllItems
          ProcessAllItems:
            Type: Parallel
            InputPath: $
            Branches:
              - StartAt: ConfigureCountEN
                States:
                  ConfigureCountEN:
                    Type: Pass
                    Parameters:
                      records.$: $.en
                      languageCode: "en"
                    ResultPath: $.iterator
                    Next: CurateData
                  CurateData:
                    Type: Pass
                    OutputPath: $.iterator
                    Next: IteratorEN
                  IteratorEN:
                    Type: Task
                    Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-iterator"
                    Next: IsCountReachedEN
                  IsCountReachedEN:
                    Type: Choice
                    Choices:
                      - Variable: $.continue
                        BooleanEquals: true
                        Next: ComputeSentimentEN
                    Default: DefaultStateEN
                  ComputeSentimentEN:
                    Type: Task
                    Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-computeSentiment"
                    ResultPath: $.result
                    Next: IteratorEN
                  DefaultStateEN:
                    Type: Pass
                    Parameters:
                      continue.$: $.continue
                    End: true
              - StartAt: ConfigureCountES
                States:
                  ConfigureCountES:
                    Type: Pass
                    Parameters:
                      records.$: $.es
                      languageCode: es
                    ResultPath: $.iterator
                    Next: CurateDataES
                  CurateDataES:
                    Type: Pass
                    OutputPath: $.iterator
                    Next: IteratorES
                  IteratorES:
                    Type: Task
                    Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-iterator"
                    Next: IsCountReachedES
                  IsCountReachedES:
                    Type: Choice
                    Choices:
                      - Variable: $.continue
                        BooleanEquals: true
                        Next: ComputeSentimentES
                    Default: DefaultStateES
                  ComputeSentimentES:
                    Type: Task
                    Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-computeSentiment"
                    ResultPath: $.result
                    Next: IteratorES
                  DefaultStateES:
                    Type: Pass
                    Parameters:
                      continue.$: $.continue
                    End: true
            End: true

resources:
  Resources:
    ProcessedBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: sentiment-analysis-serverless-destination
    FeedbackDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: FeedbackResultTable-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S

        KeySchema:
          - AttributeName: id
            KeyType: HASH

        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
custom:
  CustomerFeedbackTable:
    name: !Ref FeedbackDynamoDbTable
    arn: !GetAtt FeedbackDynamoDbTable.Arn
  bundle:
    linting: false
